export const SIGN_IN = `SIGN_IN`;
export const SIGN_IN_SUCCESS = `SIGN_IN_SUCCESS`;
export const GET_USER_SUCCESS = `GET_USER_SUCCESS`;
export const FETCH_OFFERS = `FETCH_OFFERS`;
export const FETCH_OFFERS_SUCCESS = `FETCH_OFFERS_SUCCESS`;
export const SELECT_CITY = `SELECT_CITY`;
export const SORT_OFFERS_BY = `SORT_OFFERS_BY`;
export const OFFER_ON_HOVER = `OFFER_ON_HOVER`;
